// The database of EXEGEZIS in one file, to paste in Supabase's SQL Editor (docs/13-accounts.md):
//
//   pnpm db:setup
//
// It writes supabase/setup.sql (every file of supabase/migrations, in order, in one transaction;
// safe to apply again), copies it to the clipboard on Windows and opens the SQL Editor of the
// project in .env (NEXT_PUBLIC_SUPABASE_URL). Then: paste (Ctrl+V) and press «Run».
//
//   node scripts/db-setup.mjs --write     only writes supabase/setup.sql (the tests check it is up to date)
import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseEnv } from "node:util";

const REPO = join(import.meta.dirname, "..");
const MIGRATIONS = join(REPO, "supabase", "migrations");
const OUT = join(REPO, "supabase", "setup.sql");

/** supabase/setup.sql as it must be: the migrations, in order, in one transaction. */
export function setupSql() {
  const parts = readdirSync(MIGRATIONS)
    .filter((f) => f.endsWith(".sql"))
    .sort()
    .map((f) => `-- ============================================================\n-- ${f}\n-- ============================================================\n${readFileSync(join(MIGRATIONS, f), "utf8").trim()}\n`);
  return [
    "-- EXEGEZIS: the whole database (generated by `pnpm db:setup` from supabase/migrations; do not edit).",
    "-- Paste it in Supabase → SQL Editor and press «Run». Safe to run again: it only creates what is missing.",
    "begin;",
    "",
    ...parts,
    "commit;",
    "",
  ].join("\n");
}

if (process.argv[1] !== undefined && import.meta.filename === process.argv[1]) {
  const sql = setupSql();
  writeFileSync(OUT, sql, "utf8");
  if (process.argv.includes("--write")) process.exit(0);

  const envFile = join(REPO, ".env");
  const env = { ...(existsSync(envFile) ? parseEnv(readFileSync(envFile, "utf8")) : {}), ...process.env };
  const url = (env.NEXT_PUBLIC_SUPABASE_URL ?? env.SUPABASE_URL ?? "").trim();
  const ref = /^https:\/\/([a-z0-9]+)\.supabase\.co/.exec(url)?.[1] ?? null;
  const editor = ref === null ? "https://supabase.com/dashboard/project/_/sql/new" : `https://supabase.com/dashboard/project/${ref}/sql/new`;

  let copied = false;
  if (process.platform === "win32") {
    const r = spawnSync("powershell.exe", ["-NoProfile", "-Command", `Set-Clipboard -Value (Get-Content -Raw -Encoding UTF8 '${OUT.replace(/'/g, "''")}')`], { stdio: "ignore" });
    copied = r.status === 0;
    spawnSync("cmd.exe", ["/c", "start", "", editor], { stdio: "ignore" });
  }
  console.log(
    [
      "supabase\\setup.sql " + (copied ? "está copiado al portapapeles." : "está listo."),
      "",
      `1. En el navegador se abre el SQL Editor de tu proyecto${ref === null ? " (elige tu proyecto)" : ""}:`,
      `   ${editor}`,
      copied ? "2. Pega con Ctrl+V." : "2. Abre supabase\\setup.sql, copia todo y pégalo.",
      "3. Pulsa «Run». Debe decir «Success. No rows returned».",
      "",
      "Se puede repetir sin problema: solo crea lo que falta.",
    ].join("\n"),
  );
}
